# SilkTouchHands
# Inspired by Ranboo and DreamSMP
# This plugin is not recommended for public servers. it may cause issues
# Perfect for private roleplay servers however
#
# Coded by VisualCody
# Youtube https://www.youtube.com/channel/UC8Us8YC4frRpRPapXeuFgMw
# Twitter https://twitter.com/visual_cody
# Twitch https://twitch.tv/visualcody
# GitHub https://github.com/visual-cody
# SpigotMC https://www.spigotmc.org/members/visualcody.1184917/

## Use Permissions
## Set to true to check against Bukkit permissions
## Setting to false will allow ALL players to use Silktouch
## If no Permissions are setup it defaults to OP only
## Permision node: silktouchhands.silktouch
## Default true
use_permissions: true

## Infinity Cake
## By default this is disabled. it is kind of OP but you can enable it
## This allows you to slicktouch a cake block. This literally allows infinate food
## The DreamSMP version of this plugin allows infinate cake but its an option here as it could be too much
## Default false
infinite_cake: false